[pytest]
addopts = 
    --env dev
    --screenshot=on
    --video=retain-on-failure
    --alluredir=allure-results
    --clean-alluredir

markers = 
    smoke: Critical test
    regression: Regression test
    ui: UI test
    slow: Slow test
    flaky: Flaky test
    api: API test
testpaths = tests
